version: '3.9'

services:
  db:
    image: mysql:8.3.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
